name: Style Guide Checker
description: Runs a Style Guide Checker on changed files
author: jeefy
inputs:
  override_files:
    description: "Override the files to run Style Guide Checker on."
    required: false
    default: ''
  openai_token:
    description: "[OPENAI\_API\_KEY](https://help.openai.com/en/articles/5112595-best-practices-for-api-key-safety)"
    required: true
  all_files:
    description: "Run Style Guide Checker on all matching files."
    required: false
    default: false
  ignore_path:
    description: "GLOB defining files to ignore (e.g. **/node_modules/**)"
    required: false
    default: ''
  file_extensions:
    description: "List of file extensions to watch for changes and run Style Guide Checker against."
    required: false
    default: |
      **/*.{md,MD,html,HTML}
  style_guide:
    description: "Style Guide to use."
    required: true
    default: 'https://kubernetes.io/docs/contribute/style/style-guide/'

runs:
  using: "composite"
  steps:
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v42
      with:
        path: ${{ inputs.path }}
        files: ${{ inputs.file_extensions }}
        diff_relative: true
        files_separator: '|||'
        files_ignore_from_source_file: ''
    - name: Run Style Guide Checker on changed files
      id: style-guide-checker
      shell: bash
      run: |
        python3 -m pip install --upgrade -r requirements.txt
        python3 run.py
      env:
        ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        OVERRIDE_FILES: ${{ inputs.override_files }}
        OPENAI_API_KEY: ${{ inputs.openai_token }}
        STYLE_GUIDE: ${{ inputs.style_guide }}